### PR TITLE
Fewer whitespace tokens

### PR DESCRIPTION
**Pull request by Quaqqer**
Simple change.

Related to issue #665.

### CODE REVIEW

**Review by sornas — APPROVED** [review]

**Comment by sornas** [comment]
well, except for the tests :)

**Review by FredTheDino — APPROVED** [review]
Lgtm. Check the tests in the parser module, i think they're the ones failing. I couldn't look at the output on my phone so..

**Comment by Quaqqer** [comment]
How very strange, werks on my machine™️

**Comment by Quaqqer** [comment]
I get them on my desktop, maybe my laptop has an outdated version of the rust tool chain or something.

**Comment by sornas** [comment]
gah. yes, something changed in 1.58. come to think of it, i recall hitting this a while back. i'll see if i can find it.

**Comment by sornas** [comment]
https://github.com/sylt-lang/sylt-lang/issues/562

**Pull request merged**
